# Generated by Django 6.1.1 on 2026-09-11 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del escaneo', primary_key=True, serialize=False)),
                ('target_url', models.URLField(help_text='URL de la aplicación objetivo analizada', max_length=2048)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('fallido', 'Fallido')], db_index=True, default='pendiente', help_text='Estado actual del escaneo', max_length=30)),
                ('marcador', models.CharField(blank=True, help_text='Marcador único generado para esta ejecución', max_length=100)),
                ('resultado', models.JSONField(blank=True, help_text='Resultado consolidado y estructurado del descubrimiento', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detalle del error si el escaneo fracasa', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la inspección', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación de la solicitud')),
            ],
            options={
                'verbose_name': 'Escaneo de Descubrimiento',
                'verbose_name_plural': 'Escaneos de Descubrimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('chat', 'Chat Conversacional'), ('formulario', 'Formulario Prompt'), ('editor', 'Editor Contenteditable'), ('desconocido', 'Desconocido')], default='desconocido', help_text='Tipo de interfaz detectada (chat, formulario, etc.)', max_length=50)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('ws', 'WebSocket'), ('wss', 'WebSocket Secure')], default='http', help_text='Protocolo de red del canal', max_length=20)),
                ('url', models.URLField(help_text='URL o endpoint exacto de comunicación con la IA', max_length=2048)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('WS_FRAME', 'WebSocket Frame')], default='POST', help_text='Método HTTP o trama WebSocket', max_length=20)),
                ('content_type', models.CharField(default='application/json', help_text='Tipo de contenido (Content-Type) de la petición', max_length=255)),
                ('input_mode', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio'), ('archivo', 'Archivo'), ('multipart', 'Multipart'), ('mixto', 'Mixto'), ('desconocido', 'Desconocido')], default='texto', help_text='Modo de entrada de datos (texto, audio, archivo)', max_length=50)),
                ('prompt_field', models.CharField(blank=True, help_text='Ruta exacta del campo del prompt (ej. messages[0].content)', max_length=255, null=True)),
                ('response_mode', models.CharField(choices=[('json', 'JSON'), ('sse', 'Server-Sent Events'), ('websocket', 'WebSocket'), ('chunked', 'Chunked Transfer'), ('text_plain', 'Texto Plano'), ('desconocido', 'Desconocido')], default='json', help_text='Formato de respuesta (json, sse, websocket, chunked)', max_length=50)),
                ('authentication_required', models.BooleanField(default=False, help_text='Indica si se detectó necesidad de credenciales')),
                ('authentication_types', models.JSONField(default=list, help_text='Tipos de autenticación detectados (sin credenciales)')),
                ('confidence', models.FloatField(default=0.0, help_text='Puntuación de confianza de la detección (0.0 a 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(help_text='Escaneo al que pertenece este canal', on_delete=django.db.models.deletion.CASCADE, related_name='ai_channel', to='backend_genvulnai.discoveryscan')),
            ],
            options={
                'verbose_name': 'Canal de IA',
                'verbose_name_plural': 'Canales de IA',
            },
        ),
        migrations.CreateModel(
            name='NetworkObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_url', models.TextField(help_text='URL de la petición observada')),
                ('method', models.CharField(help_text='Método HTTP o WS', max_length=30)),
                ('resource_type', models.CharField(blank=True, help_text='Tipo de recurso según navegador (fetch, xhr, websocket, etc.)', max_length=50)),
                ('sanitized_headers', models.JSONField(default=dict, help_text='Cabeceras HTTP sanitizadas (sin tokens ni secretos en texto plano)')),
                ('sanitized_body', models.TextField(blank=True, default='', help_text='Cuerpo de la petición sanitizado y truncado')),
                ('response_status', models.IntegerField(blank=True, help_text='Código de respuesta HTTP', null=True)),
                ('response_content_type', models.CharField(blank=True, default='', help_text='Content-Type de la respuesta', max_length=255)),
                ('contains_marker', models.BooleanField(db_index=True, default=False, help_text='Indica si esta petición transmitió el marcador de prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(help_text='Escaneo asociado', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='backend_genvulnai.discoveryscan')),
            ],
            options={
                'verbose_name': 'Observación de Red',
                'verbose_name_plural': 'Observaciones de Red',
                'ordering': ['created_at'],
            },
        ),
    ]
