# Generated by Django 6.1.1 on 2026-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryscan',
            name='ia_habilitada',
            field=models.BooleanField(default=True, help_text='Indica si el análisis semántico con IA (Ollama) estaba activo para este escaneo'),
        ),
        migrations.AddField(
            model_name='discoveryscan',
            name='ia_modelo',
            field=models.CharField(blank=True, default='', help_text='Modelo local de Ollama utilizado (ej. llama3.2)', max_length=100),
        ),
        migrations.AddField(
            model_name='discoveryscan',
            name='ia_utilizada',
            field=models.BooleanField(default=False, help_text='Indica si se recurrió a Ollama para resolver ambigüedades en este escaneo'),
        ),
    ]
