# Generated by Django 6.1.1 on 2026-09-16 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0002_discoveryscan_ia_habilitada_discoveryscan_ia_modelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la sesión de ataque', primary_key=True, serialize=False)),
                ('objetivo', models.TextField(help_text='Meta o consigna asignada al agente atacante A1 (ej: extraer system prompt)')),
                ('max_turnos', models.IntegerField(default=20, help_text='Límite máximo de turnos antes de detener el ataque')),
                ('turnos_ejecutados', models.IntegerField(default=0, help_text='Cantidad de turnos efectivamente completados')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('exito', 'Éxito (Meta Cumplida)'), ('max_turnos', 'Límite de Turnos Alcanzado'), ('fallido', 'Fallido por Error')], db_index=True, default='en_proceso', help_text='Estado actual de la sesión de ataque', max_length=30)),
                ('puntaje_maximo', models.IntegerField(default=0, help_text='Máximo puntaje alcanzado por el evaluador (0-10)')),
                ('exito', models.BooleanField(default=False, help_text='Indica si se alcanzó la meta (puntaje == 10)')),
                ('modelo_a1', models.CharField(blank=True, default='', help_text='Modelo local de Ollama utilizado como agente atacante A1', max_length=150)),
                ('modelo_j1', models.CharField(blank=True, default='', help_text='Modelo local de Ollama utilizado como juez evaluador J1', max_length=150)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la sesión fracasó inesperadamente', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la sesión', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Fecha y hora de finalización', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de creación')),
                ('scan', models.ForeignKey(help_text='Escaneo de descubrimiento origen que identificó el endpoint', on_delete=django.db.models.deletion.CASCADE, related_name='attack_sessions', to='backend_genvulnai.discoveryscan')),
            ],
            options={
                'verbose_name': 'Sesión de Ataque',
                'verbose_name_plural': 'Sesiones de Ataque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttackTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del turno', primary_key=True, serialize=False)),
                ('numero_turno', models.IntegerField(help_text='Número ordinal del turno (1, 2, 3...)')),
                ('prompt_a1', models.TextField(help_text='Payload / prompt generado por A1 para este turno')),
                ('tactica_usada', models.CharField(blank=True, default='', help_text='Nombre de la táctica seleccionada por A1 o recuperada de ChromaDB', max_length=150)),
                ('respuesta_d1', models.TextField(blank=True, default='', help_text='Texto devuelto por la IA objetivo (D1)')),
                ('status_code_d1', models.IntegerField(blank=True, help_text='Código HTTP recibido del endpoint D1', null=True)),
                ('latencia_d1_ms', models.FloatField(blank=True, help_text='Latencia de respuesta del endpoint D1 en milisegundos', null=True)),
                ('puntaje_j1', models.IntegerField(blank=True, help_text='Puntuación otorgada por el juez J1 (1-10)', null=True)),
                ('justificacion_j1', models.TextField(blank=True, default='', help_text='Razonamiento emitido por el juez J1')),
                ('fuga_detectada', models.BooleanField(default=False, help_text='Indica si J1 detectó filtración de datos sensibles o cumplimiento de meta')),
                ('fragmentos_fuga', models.JSONField(blank=True, default=list, help_text='Fragmentos específicos extraídos como evidencia por J1')),
                ('fue_reset', models.BooleanField(default=False, help_text='Indica si este turno fue forzado por un reinicio de estrategia (A1 reset)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de ejecución del turno')),
                ('session', models.ForeignKey(help_text='Sesión de ataque asociada', on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='backend_genvulnai.attacksession')),
            ],
            options={
                'verbose_name': 'Turno de Ataque',
                'verbose_name_plural': 'Turnos de Ataque',
                'ordering': ['session', 'numero_turno'],
            },
        ),
    ]
