# Generated by Django 6.1.1 on 2026-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0003_attacksession_attackturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksession',
            name='persistencia_habilitada',
            field=models.BooleanField(default=False, help_text='Indica si se solicitó persistencia para este ataque'),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='persistencia_turnos_refuerzo',
            field=models.IntegerField(default=10, help_text='Cantidad de turnos de refuerzo para el Vector 2'),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='persistencia_turnos_verificacion',
            field=models.IntegerField(default=5, help_text='Cantidad de turnos de verificación inocuos'),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='persistencia_verificada',
            field=models.BooleanField(default=False, help_text='Indica si se confirmó la persistencia del ataque en D1'),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='resultado_persistencia',
            field=models.JSONField(blank=True, help_text='Detalle estructurado de la fase de persistencia', null=True),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='vectores_persistencia',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de vectores de persistencia a ejecutar [1, 2, 3]'),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='es_persistencia',
            field=models.BooleanField(default=False, help_text='Indica si este turno pertenece a la fase de persistencia'),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='vector_persistencia',
            field=models.IntegerField(blank=True, help_text='Vector de persistencia ejecutado (1, 2 o 3; 0 para verificación)', null=True),
        ),
        migrations.AlterField(
            model_name='attacksession',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('exito', 'Éxito (Meta Cumplida)'), ('exito_persistido', 'Éxito con Persistencia Verificada'), ('max_turnos', 'Límite de Turnos Alcanzado'), ('fallido', 'Fallido por Error')], db_index=True, default='en_proceso', help_text='Estado actual de la sesión de ataque', max_length=30),
        ),
    ]
