# Generated by Django 6.1.1 on 2026-09-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0004_attacksession_persistencia_habilitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackturn',
            name='categoria_ataque',
            field=models.CharField(choices=[('inyeccion_directa', 'Inyección Directa'), ('fuga_instrucciones', 'Fuga de Instrucciones del Sistema'), ('confusion_delimitadores', 'Confusión de Delimitadores'), ('suplantacion_rol', 'Suplantación de Rol / Roleplay'), ('inyeccion_oculta', 'Inyección Oculta / Cifrada'), ('evasion_restricciones', 'Evasión de Restricciones (Jailbreak)'), ('desconocida', 'Desconocida / No Clasificada')], default='desconocida', help_text='Categoría taxonómica del vector de ataque empleado', max_length=64),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='clasificacion_resultado',
            field=models.CharField(choices=[('resistido', 'Ataque Resistido (Defensa Efectiva)'), ('parcial', 'Cumplimiento Parcial (Desvío Leve)'), ('exito', 'Ataque Exitoso (Vulnerabilidad Confirmada)'), ('error_sistema', 'Error del Sistema Objetivo (HTTP 500 / Timeout)'), ('inconcluso', 'Inconcluso / No Determinable')], default='inconcluso', help_text='Clasificación cualitativa del resultado del turno según el juez', max_length=64),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='confianza_evaluacion',
            field=models.FloatField(default=1.0, help_text='Nivel de certidumbre del dictamen (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='formato_preservado',
            field=models.BooleanField(default=True, help_text='Indica si D1 mantuvo su formato sintáctico esperado'),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='instruccion_adversaria_seguida',
            field=models.BooleanField(default=False, help_text='Indica si D1 ejecutó la instrucción adversaria inyectada'),
        ),
        migrations.AddField(
            model_name='attackturn',
            name='tarea_preservada',
            field=models.BooleanField(default=True, help_text='Indica si D1 ejecutó la tarea legítima en lugar del payload malicioso'),
        ),
    ]
