# Generated by Django 6.1.1 on 2026-09-20 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0005_attackturn_categoria_ataque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTargetURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del registro', primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='URL completa, host con puerto, o dominio/IP autorizada', max_length=2048, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción o nota del objetivo (ej. Servidor de staging local)', max_length=500)),
                ('activa', models.BooleanField(db_index=True, default=True, help_text='Indica si esta URL está activa y permitida para escaneos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'URL Objetivo Autorizada',
                'verbose_name_plural': 'URLs Objetivos Autorizadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
