# Generated by Django 5.2.17 on 2026-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_genvulnai', '0006_allowedtargeturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryscan',
            name='software_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID del Software objetivo asociado en el módulo de pruebas (Logical FK)', null=True),
        ),
    ]
